try{
    let a;
    console.log(a.length);
    console.log(`should'nt print this ..`);
    
}catch(e){
    console.log(`inside catch`);
}
console.log(`end of code`);